### ISSUE TITLE
Disable mod with Kerbalism installed

### ISSUE THREAD

**Issue by ChrisAdderley** [ChrisAdderley/DynamicBatteryStorage#48]
Need to make this mod turn itself off when Kerbalism is installed in order to not confuse users.

**Comment by SirMortimer** [comment]
Since Kerbalism 3.1 (released yesterday) we check against a list of known mods to see if something is missing or conflicting. If a mod with known incompatibility is found, the player gets a warning message that essentially suggest to remove that mod. DynamicBatteryStorage is on the list of mods Kerbalism will complain about.

The intention is to avoid exactly this type of situation, to help the user to get a sane and clean KSP installation and warn him about possible problems right from the start.

**Comment by VasVadum** [comment]
But, if this mod is required by certain things like Near Future Electrical and a bunch of others, why would removing it be a good idea? I don't want to lose out on everything else, just to have Kerbalism.

**Comment by SirMortimer** [comment]
KSP doesn't have a good handling of resources being generated and consumed at high time warp speeds: resource production/consumption rates scale with time warp, but storage capacity does not. So DBS increases the electrical storage capability of your vessel during time warp, and reduces it again when you come out of time warp. Kearbalism deals with the same time warp problem, but differently (in a nutshell, we replace the stock KSP resource handling with our own which also works for unloaded vessels, and keep the results in sync with KSP after each simulation step).

Having both mods doing this at the same time will lead to inconsistent behaviours, it will confuse the heck out of Kerbalism and possibly result in unwarranted death of Kerbals.

By removing DBS, you will still be able to use the parts of NearFutureElectrics, but you will also loose all the cool stuff from DBS (vessel monitoring & planning in the VAB).

**Comment by SirMortimer** [comment]
FWIW I couldn't reproduce #46 with Kerbalism.

**Comment by ChrisAdderley** [comment]
@VasVadum The procedure for handling Kerbalism is purely to offload all support to that mod. When you install any of my mods, you are effectively getting parts whose art is mine but functionality is Kerbalism's. That is the cleanest way to handling this in my view.
