### ISSUE TITLE
Ship randomly stops consuming EC and solar planner is broken.

### ISSUE THREAD

**Issue by EnderiumSmith** [ChrisAdderley/DynamicBatteryStorage#69]
Im using ksp 1.8

While flying ships powered by solar panels with this mod installed, the electric charge will randomly get stuck to max and will not deplete even when transmitting data. this happens even if the ship is behind a planet. it changes between stuck and normal while time warping long distances. just entering warp for a moment doesnt cause it to change. It also doesnt happen on nuclear ships though kerbal atomics has its own problems.

Also the solar planner in the VAB does not display solar power correctly. In one case it was saying it should be 150% but it actually was 300%. It also does not take into account other stars.

In flight the menu that lists production and consumption does show the correct numbers for nft propulsion engine, but much lower ones, even though the engines themselves are consuming the correct amount and the VAB planner does show the correct values

Also what would happen if i removed this mod? would the nft mods break?

**Comment by ChrisAdderley** [comment]
Overall, to actually debug issues I need a lot more information. Logs, mod lists, how I can reproduce the issue. 

> Also the solar planner in the VAB does not display solar power correctly. In one case it was saying it should be 150% but it actually was 300%. It also does not take into account other stars.

This is a known issue and will be fixed in the next version. Other star support is not on the roadmap.

> While flying ships powered by solar panels with this mod installed, the electric charge will randomly get stuck to max and will not deplete even when transmitting data. this happens even if the ship is behind a planet. it changes between stuck and normal while time warping long distances. just entering warp for a moment doesnt cause it to change. It also doesnt happen on nuclear ships though kerbal atomics has its own problems.

It sounds like you might be running into a compatibility issue between Koperniucus 1.8 and the later versions on this mod. Use an earlier version of DBS (2.1.8 or lower) and see if there are any issues.  
> kerbal atomics has its own problems.
This doesn't tell me what's going on.
> In flight the menu that lists production and consumption does show the correct numbers for nft propulsion engine, but much lower ones, even though the engines themselves are consuming the correct amount and the VAB planner does show the correct values

Which engines? I just had a look at it seems fine. Screenshots?

> Also what would happen if i removed this mod? would the nft mods break?
You can use without it, but I will not provide any support if you run into issues (and you will)

**Comment by EnderiumSmith** [comment]
I installed the latest version for 1.8 and it seem to make not difference. The probe can burn ions without depleting power even though the panels are only providing 30% of the power. The menu even lists the balance as highly negative.

It does show the engine consumption correctly this time at least.

what kind of issues would i run into. the problem its supposed to solve isnt really a problem. Theres no reason to use such high warps outside the tracking station.

Oh and about kerbal atomics: The reactor and engine can run one without the other, with bad results, and the throttle override for the reactor is at 100 by default. Nuclear jet engines's reactors dont throttle with the engine's pressure/velocity curves. Running the engines at lower throttle reduces isp but i see no reason it cant hold the heat at lower thermal output if the propellant flow is lower. And you can Z X it to instantly go from 0 to 100 and back. The dissipated heat doesnt scale with heat so you can let it reach higher temps before turning on the thrust and it will stay there. The garnet and nerv are the same reactor in thermal output but the garnet lasts years while the nerv lasts days. this makes the ec generation of the trimodal engines useless as it will very quickly eat the fuel. if you forget a reactor on idle and time warp in the racking station a long time, when you return a lot of uranium will be gone and if you leave it too long it explodes.

![Screenshot from 2020-09-17 21-18-58](https://user-images.githubusercontent.com/20334653/93527033-fa40df00-f940-11ea-8918-02cff6cf6d21.png)

**Comment by ChrisAdderley** [comment]
> I installed the latest version for 1.8 and it seem to make not difference. The probe can burn ions without depleting power even though the panels are only providing 30% of the power. The menu even lists the balance as highly negative.

So, this mod doesn't change consumption at all, only tracks it. The UI is the plugin's understanding of the electricity state, so that's what it thinks is happening. The screenshot even shows that most of the mod's features are disabled at the moment (things only happen over 100x time warp).
You can give me logs, but I don't have time to dig into them right now (life). I can say that you should go investigate Kopernicus - they always have challenges handling panels in multiple star systems, and if this issue is only happening with panels, I really doubt it has much to do with this mod.

> what kind of issues would i run into. the problem its supposed to solve isnt really a problem. Theres no reason to use such high warps outside the tracking station.

There absolutely is, people do it all the time. This issue can manifest at almost any time warp, depending on the electricity storage of your ship compared to the consumers and producers.

> Oh and about kerbal atomics: The reactor and engine can run one without the other, with bad results, and the throttle override for the reactor is at 100 by default. Nuclear jet engines's reactors dont throttle with the engine's pressure/velocity curves. Running the engines at lower throttle reduces isp but i see no reason it cant hold the heat at lower thermal output if the propellant flow is lower. And you can Z X it to instantly go from 0 to 100 and back. The dissipated heat doesnt scale with heat so you can let it reach higher temps before turning on the thrust and it will stay there. The garnet and nerv are the same reactor in thermal output but the garnet lasts years while the nerv lasts days. this makes the ec generation of the trimodal engines useless as it will very quickly eat the fuel. if you forget a reactor on idle and time warp in the racking station a long time, when you return a lot of uranium will be gone and if you leave it too long it explodes.

Sounds like you don't like the gameplay model; I don't really have time to get into how to use the *optional* thing, but I'd say just don't install it.
